version: '3'

services:
  # apache2
  www:
    image: httpd:2.4
    ports: 
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      - db
    networks:
      - dbphp
  # mysql database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: database-tester
      MYSQL_PASSWORD: password
    networks:
      - dbphp
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - dbphp
networks:
  dbphp:
volumes:
  db_data: