Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu Master"
    vb.gui = false
    vb.cpus = 4
    vb.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Copy the setup bash script.
    sudo cp /vagrant/setup-docker-compose.sh /home/vagrant/
    # Make the bash script executable.
    sudo chmod +x /home/vagrant/setup-docker-compose.sh
    # Create a directory for the docker-compose.yaml file and move the file to that folder.
    sudo mkdir /home/vagrant/docker
    sudo cp /vagrant/docker-compose.yaml /home/vagrant/docker
    # Run the bash script
    sudo bash /home/vagrant/setup-docker-compose.sh
  SHELL
end