# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4443
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8001, host: 8001
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Wordpress Testing"
    vb.gui = false
    vb.memory = "6144"
    vb.cpus = 4
  end

  #config.vm.provision "shell", inline: <<-SHELL
  #SHELL

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "lamp-playbook.yml"
  #end
end